### ISSUE TITLE
RS232 <> 485 converter

### ISSUE THREAD

**Issue by paulobriennz** [reaper7/SDM_Energy_Meter#1]
## DONT WORRY, found link in your blog :)

Awesome! Have been looking for example like this!  Thank you so much for posting.

Could you please tell me what the model of your rs232<->rs485 converter with automatic flow direction control unit is please?

Many thanks!
Paul

**Comment by reaper7** [comment]
look at bottom of my post (aliexpress link):
http://www.esp8266.com/viewtopic.php?p=51796#p51796

**Comment by ilgrank** [comment]
Hi
At low bitrates (9600baud) shouldn't the ESP8266 alone be enough to read an RS485 without a converter?
[](https://github.com/plieningerweb/esp8266-software-uart)

**Comment by reaper7** [comment]
as wrote in this issue:
https://github.com/reaper7/SDM_Energy_Meter/issues/6#issuecomment-270925033
