### ISSUE TITLE
SDM 120C problem with ESPcore newer than 2.4.0 rc2

### ISSUE THREAD

**Issue by Giobax** [reaper7/SDM_Energy_Meter#15]
No probem when I use the library with ESP core 2.4.0 rc 2...but updating to 2.4.0 or 2.4.1 it cause al lot of "na". Using wemos D1 mini and a SDM120 on D2 and D1. Any solution? 
Giovanni.

**Comment by reaper7** [comment]
You are using softwareor hardware serial?
I did not notice errors increase when hardware serial is used.

**Comment by reaper7** [comment]
Sorry...I see D2/D1 this mean softwareserial...
Please try to upgrade Your SoftwareSerial library and read this issue:
https://github.com/plerup/espsoftwareserial/issues/63

**Comment by reaper7** [comment]
Closing due to lack of feedback.
