### ISSUE TITLE
How to set SERIAL_8E1

### ISSUE THREAD

**Issue by wirelesssolution** [reaper7/SDM_Energy_Meter#21]
Can I set SERIAL_8E1 ? because I use this lib for another Digital Meter.

**Comment by reaper7** [comment]
Currently it is not possible from sketch(only default 8N1).
Of course, you can change this by editing sdm.h file https://github.com/reaper7/SDM_Energy_Meter/blob/master/SDM.h#L200

**Comment by reaper7** [comment]
@wirelesssolution - you can try new library version, which supports the hardware uart configuration.
