### ISSUE TITLE
Problem compiling with arduino IDE 1.8.6+ and hardware serial

### ISSUE THREAD

**Issue by v-a-d-e-r** [reaper7/SDM_Energy_Meter#23]
Hello all. I'm running mad now. With software serial everything works fine, with hardware serial I can't even compile and get this error:

Code:
#define USE_HARDWARESERIAL
#include <SDM.h>
SDM Plugin_150_SDM(Serial, 9600, NOT_A_PIN, SERIAL_8N1, false);

Error:
undefined reference to `SDM::SDM(HardwareSerial&, long, int, int, bool)'
sketch/ESPEasy.ino.cpp.o: In function `Plugin_150(unsigned char, EventStruct*, String&)':
undefined reference to `SDM::SDM(HardwareSerial&, long, int, int, bool)'
undefined reference to `SDM::SDM(HardwareSerial&, long, int, int, bool)'
collect2: error: ld returned 1 exit status

Any idea what's going wrong here?

**Comment by salberin** [comment]
Came here to write a bug report, as I am experiencing the exact same error....

**Comment by salberin** [comment]
I'm experiencing this using a Wemos D1 Mini. Are you using the same hardware?

**Comment by v-a-d-e-r** [comment]
No. I have a Lolin NodeMCU. But I think it does not depend on the hardware. More on the communication between the SDM software and the hardware serial library.

**Comment by reaper7** [comment]
Uncomment
#define USE_HARDWARESERIAL
in sdm_user_config.h file

**Comment by v-a-d-e-r** [comment]
Hi. Many thanks, it works! Can't believe it..... I thought when I define it in the .ino it is global? And #define USE_HARDWARESERIAL is before include <SDM.h>!?
