### ISSUE TITLE
Read out further registers sdm630

### ISSUE THREAD

**Issue by ralphi** [reaper7/SDM_Energy_Meter#29]
There is a PDF with all registers (SDM 630)
[https://www.varmepumpsforum.com/Eastron_SDM630_Modbus_protocol_V1.5.pdf](https://www.varmepumpsforum.com/Eastron_SDM630_Modbus_protocol_V1.5.pdf)

I needed other editions and I simply expanded the SDM.h:

#define SDM630_IMPORT1                		0x015a                              //kWh
#define SDM630_IMPORT2                		0x015c                              //kWh
#define SDM630_IMPORT3                		0x015e                              //kWh

#define SDM630_EXPORT1                		0x0160                              //kWh
#define SDM630_EXPORT2                		0x0162                              //kWh
#define SDM630_EXPORT3                		0x0164                              //kWh

#define SDM630_TOTAL_ENERGY1           		0x0166                              //kWh
#define SDM630_TOTAL_ENERGY2                0x0168                              //kWh
#define SDM630_TOTAL_ENERGY3                0x016a                              //kWh

**Comment by reaper7** [comment]
the document shows that it is kWh not Wh

**Comment by ralphi** [comment]
Yes - corrected :-)

**Comment by reaper7** [comment]
done!
