### ISSUE TITLE
Gives Nan value always by SDM230 using ESP32

### ISSUE THREAD

**Issue by rafi021** [reaper7/SDM_Energy_Meter#30]
Hello,
I am using ESP32 module to interface with SDM230 Modbus device with TXpin -4 and RXpin-25 and DERE control pin-2, baudrate set for both device is 2400 (both in ESP32 and SDM230). But always gives nan value of all readings. Also i checked the error code which is 3 and 4 most of the times. I tried different ways but still no luck. Please add support for this nice chip ESP32 for SDM230 devices. 

Thanks

**Comment by reaper7** [comment]
You are trying to do with Software or Hardware serial implementation?

**Comment by balucio** [comment]
I had the same problems using Software Serial and ESP8266 with Arduino IDE / ESP8266 v.2.5.2. I think problem is in the EspSoftwareSerial that came with Esp library. I had to use hardware serial.

**Comment by reaper7** [comment]
closed due to inactivity
