### ISSUE TITLE
Live example causes esp8266-12E(F) to constantly reboot cause of the wdt

### ISSUE THREAD

**Issue by PyroRider** [reaper7/SDM_Energy_Meter#42]
Tried to use code on esp8266 12e(f), but it always reboots after a couple of seconds because the wdt resets it
Any ideas? (btw i tried example webserver, works fine)

**Comment by reaper7** [comment]
sdm_simple example causes wtd too?

**Comment by PyroRider** [comment]
Ps ist good usb cable on pc, found out there was a problem with the sdm library, probably cause i "shrinked" the library down to minimal needed stuff for my arduino to work. Reinstalled library, now its working (probably) fine, just need to connect max485 to the esp
