### ISSUE TITLE
[Not an issue] Rewriting some stuff in your library and upload it?

### ISSUE THREAD

**Issue by PyroRider** [reaper7/SDM_Energy_Meter#47]
Hello reaper7, I am currently rewriting some of the stuff in your library as I want to use it with an ESP and ann ABB energy meter. Would it be ok if I upload my rewritten files to git and mention that it's based on your library?
Greeting from Germany :)

**Comment by reaper7** [comment]
no problem, maybe I will get some interesting solutions from you repo :)
