### ISSUE TITLE
Multiple SDM with a single ESP32

### ISSUE THREAD

**Issue by maxdd** [reaper7/SDM_Energy_Meter#56]
Hello,
I admit i have low knowledge on how the library works but i know about master/slave Modbus concept.
I was wondering whether a "multiple sdm environment" can work on a single esp32.
The idea is to monitor multiple AC line and i was wondering whether it will be sufficient to connect a single RS485-TTL board as such

![](https://electrical-engineering-portal.com/wp-content/uploads/2016/12/2-wire-rs485-connection.png)

and if it will be sufficient to have different slave addresses

Regards,

**Comment by reaper7** [comment]
yes, one esp + one converter is enough 
and of course different slave address on each meter

**Comment by maxdd** [comment]
where do you normally source this devices? from aliexpress it takes quite a lot.
I briefly looked through the code but haven't seen any api to set the slave address or anything else.
What do you normally use?

**Comment by reaper7** [comment]
I bought one device a long time ago, I don't have the others.

I set the slave address and transmission parameters on the meter, the SDM220 has this functionality.

This lib allow only read from 3X input registers.

**Comment by maxdd** [comment]
Ok, i might as well extend this library when i decide to dive in my project

**Comment by reaper7** [comment]
on github you will find libraries that fully support the modbus protocol
