### ISSUE TITLE
_Plugin_Helper.h No such file or directory

### ISSUE THREAD

**Issue by maximinus333** [reaper7/SDM_Energy_Meter#78]
Hi All,
as  newbie on Arduino I cant resolve this error message when trying to upload _P078__Eastron.ino to my Wemos D1 via Arduino 1.8.19
I tried to include SDM.h and SDM_Config_User.h

but still same error .
How can I resolve this?

Regards Gerhard

**Comment by reaper7** [comment]
Hi,
_P078__Eastron.ino and _Plugin_Helper.h are not files from this repository.
You need to seek help from the creator of that sketch.

**Comment by TD-er** [comment]
Sounds like those are for ESPEasy :)
